Feature branch setup
karthykarthick/React-calculator pull request #2
Opened 2021-03-04 17:38 UTC by karthykarthick

In this one i implemented everything as per the requirements

   - Initialize a git repo

   - Create a Heroku app

   - Commit and deploy to Heroku

   - Make sure the Heroku app works correctly

   - Push everything to Github

2021-03-04 20:05 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @karthykarthick, congratulations on this project :partying_face: Awesome :+1: App created with create-react-app :1st_place_medal: PR and README file professional :fireworks: Live link working correctly :slightly_smiling_face: However, let us kindly address the requirements that ae not met:
- Kindly add big.js and prop-types to our package.json file
- Kindly remove unnecessary files or assets like the logo.svg, reportWebVitals, or one of the CSS file

Once these are fixed, kindly submit another code review request :smile: 
_Hapy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-03-04 20:05 UTC, addod19 commented on package.json
> +    "stylelint": "^13.3.3",
Kindly add big.js and prop-types to package.json file

2021-03-04 22:18 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @karthykarthick :hand: 
Nice job so far but we need to make some changes before moving on.

- [ ] We need to update the README file by adding descriptive information about the project. Right now the README lacks relevant information about the project since it still has the placeholder text generated by `create-react-app`.
![Screenshot from 2021-02-03 13-37-02](https://user-images.githubusercontent.com/30977845/106778665-f8906300-6624-11eb-9672-7ca6cff8dde8.png)

- [ ] All code from the index.js file was deleted. Our app should at least start using React. Your index file should have at least:
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

```

- [ ] We also need to have the App.js file. The component should be as simple as this.

```JS
import React from 'react'

const App = () => {
  return (
    <h1>Hello World</h1>
  )
}
```

Happy coding :computer: 
**Sérgio Torres**

2021-03-08 17:30 UTC, bellom commented
> ### Changes required 💪
> Hi @karthykarthick ✋
> Nice job so far but we need to make some changes before moving on.
> 
> * [ ]  We need to update the README file by adding descriptive information about the project. Right now the README lacks relevant information about the project since it still has the placeholder text generated by `create-react-app`.
>   ![Screenshot from 2021-02-03 13-37-02](https://user-images.githubusercontent.com/30977845/106778665-f8906300-6624-11eb-9672-7ca6cff8dde8.png)
> * [ ]  All code from the index.js file was deleted. Our app should at least start using React. Your index file should have at least:
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> import App from './App';
> 
> ReactDOM.render(
>   <React.StrictMode>
>     <App />
>   </React.StrictMode>,
>   document.getElementById('root')
> );
> ```
> 
> * [ ]  We also need to have the App.js file. The component should be as simple as this.
> 
> ```js
> import React from 'react'
> 
> const App = () => {
>   return (
>     <h1>Hello World</h1>
>   )
> }
> ```
> 
> Happy coding 💻
> **Sérgio Torres**

@karthykarthick Kindly make the changes mentions in this comment by @Torres-ssf 

Just like your heroku link, which display `hello`, running your app locally doesn't show that.

2021-03-08 17:34 UTC, bellom requested changes
## Hi @karthykarthick   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**Kindly check out my quote comment above**


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-03-08 18:53 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

## Congratulations @karthykarthick :tada: 

### This project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

**Comment(s)**
- For projects divided into milestones, always push your code to production whenever you're done with a particular feature/milestone.

Again, congratulations, you can now merge to development.
Do not forget to fill the project completion form.

**_Good luck with your next project._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-09 19:58 UTC, merged